export const accountStatementData = {
    "trxType": {
        "Purchase Payment (PayPak, Visa)": "POS Payment",
        "Auto Debit": "Auto Debit",
        "IBFT Outgoing OTC": "Agent Outgoing IBFT",
        "PTS Purchase Payment (Mastercard)": "POS Payment",
        "Bank Cash In for Ordinary ORG and Customer": "Transfer from Bank",
        "G2P Collecting": "Local Remittance Collection",
        "Bank Cash Out for Ordinary ORG and Customer": "Transfer to Bank",
        "Business Cash Out": "Business Cash Out",
        "PTS QR Issuance": "Virtual Card Issuance Fee",
        "Profit Disburse": "Profit Disburse",
        "Account Adjustment Bulk": "Account Adjustment",
        "Business Cash In": "Business Cash In",
        "Purchase Payment Reversal": "POS Reversal",
        "G2P Payment": "Local Remittance Transfer",
        "Redeem Loyalty Points": "Loyalty Points Redemption",
        "Auto Debit Account inactivity": "Account Inactivity Fee",
        "International Remittance": "Foreign Remittance",
        "Transfer(B2B)": "Money Transfer",
        "Purchase Payment": "POS Payment",
        "IBFT Credit": "Incoming IBFT",
        "MFS Card Withdraw": "ATM Withdrawal",
        "Get Loan": "Loan Request",
        "Cash in": "Incoming Amount",
        "Jazz Load (Prepaid top-up)": "Prepaid Top-up",
        "Transfer(B2C)": "Money Transfer",
        "Utility Bills Payment": "Utility Bills Payment",
        "Cash out": "Retailer Cash Out",
        "Merchant Payment": "Merchant Payment",
        "Collecting": "UBP Collection",
        "Donation": "Donation",
        "PTS Purchase Payment": "Debit Card Payment",
        "PTS ATM Withdrawal": "ATM Withdrawal",
        "IBFT Outgoing Customer": "Money Transfer",
        "Transfer(C2C)": "Money Transfer",
        "Card Order Charge": "Card Order Fee",
        "Indigo Bills (Postpaid payment)": "Postpaid Payment",
        "Online Payment": "Online Payment",
        "Transfer(C2B)": "Money transfer",
        "Customer Remit To CNIC": "Money transfer",
        "Refund Merchant Payment": "Payment Reversal",
        "RAAST Refund": "RAAST Reversal",
        "Card Order Charge Refund": "Card Order Fee Reversal",
        "PTS Purchase Payment Reversal": "POS Reversal",
        "PTS ATM Withdrawal Reversal": "ATM reversal",
        "Business Cash Out": "Business Cash Out",
        "PTS QR Issuance": "Virtual Card Issuance Fee",
        "Reversal MFS Card Withdraw": "ATM withdrawal reversal",
        "Account Adjustment": "Account Adjustment",
        "Business Cash In": "Business Cash In",
        "Purchase Payment Reversal": "POS Reversal",
        "G2P Payment": "Local Remittance Collection"
    },
    "channel": {
        "NEW_JC_APP": "JazzCash App",
        "NEW JC APP": "JazzCash App",
        "New JC App": "JazzCash App",
        "USSD": "USSD",
        "Business App": "Merchant App",
        "ATM": "ATM",
        "USSD_API": "USSD",
        "USSD API": "USSD",
        "THIRD_PARTY_WEB": "JazzCash",
        "THIRD PARTY WEB": "JazzCash",
        "Mobile App": "JazzCash App",
        "Web": "USSD",
        "Payment Gateway": "JazzCash App",
        "QR Payment": "JazzCash App",
        "Self Care App": "JazzCash App"
    }
}