apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler
metadata:
  name:  analytics-microservice-hpa 
  namespace:  m11s
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: analytics-microservice
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
