apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: analytics-consumer
  namespace:  jc-pre-prod-microservices
spec:
  to:
    kind: Service
    name: analytics-consumer
  port:
    targetPort: 3000-tcp
  
