apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler
metadata:
  name:  analytics-consumer-hpa 
  namespace:  m11s
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: analytics-consumer
  minReplicas: 25
  maxReplicas: 25
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
