apiVersion: autoscaling/v2beta1 
kind: HorizontalPodAutoscaler
metadata:
  name:  analytics-microservice-hpa 
  namespace:  m11s
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1 
    kind: DeploymentConfig 
    name: analytics-microservice
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
