kind: Service
apiVersion: v1
metadata:
  name: analytics-consumer
  namespace:  m11s
  labels:
    app: analytics-consumer
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: analytics-consumer
    deployment: analytics-consumer
  type: NodePort
  sessionAffinity: None
status:
  loadBalancer: {}
